language: node_js
node_js:
- '6'
branches:
  only:
  - master
before_install:
- npm install -g gulp jspm
after_success:
- test $TRAVIS_TEST_RESULT = 0 && gulp release
env:
  - SAUCE_USERNAME=jonhyper
addons:
  jwt:
    saucelabs:
      secure: jv1ChzT+CWABmjZ1KbmDByIJaeEVYQlccnmZDHIIOP3ZPvRgp7n8JxSZh6yqkhectZsgKpOV8S8DGRisSy89HJmAvoQb74EN70lZu3yCuGPexgc4be4kL8fKmH/Ik1AJLhqHrxQPl9RlMC/YPWHMJJBWScApMJ5ojhvXAhgVS2baEQfrJ5jjyi3/d/DaarPPTUUA6hzZDjRI6eshAMwN+L6/GM4379MCGbuTVIcZMyjCHcl3tZ+N2Q8bMHTet2YghbqH5HSRlam/R6zbxS62YrEZiDhKWKm0LULrDNRLg9dx7ICoS2avyKKd8jhe8VmAfNeLaWcUO6WYJrTxtgC1avkfzNOUkPTPjybHmiIuzXPivX55vKJ7l1E82WniREYi2vd7cOZSwZOAgtjNIrQk1xtfDFX2C5p7b4tCifhgs+xeWycCyt8Qx5htdsOJPHVO1cpGt4ORQoqtmQol3efCeFqpyf4414a8FsgBw09dhnjYvqsIhQnsvWsn1G0ZuNkv6HkuXraIWodBkeXczzIKjhhH97WnUGkUt7E5KMCumt5FCVgTPV3tdPr5PjE7fcjbUOHCFm3ZqJonG4CtWZqy+xF4VsM9HCjQFojVn9CD9M8p1oYkuFPosJ0qLlpY6nE4ZuuU6ZlM3HNmCbXCmypdDj5gh4sUPeVP8zci3JU30+Y=
